spring.application.name=order-service

server.port=8082

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/order_db}
spring.datasource.username=${DATABASE_USERNAME:order_user}
spring.datasource.password=${DATABASE_PASSWORD:order_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

catalog.service.url=${CATALOG_SERVICE_URL:http://localhost:8081}

aws.region=${AWS_REGION:eu-west-1}
sqs.queue.url=${SQS_QUEUE_URL:http://localhost:4566/000000000000/order-created-queue}
sqs.endpoint=${SQS_ENDPOINT:}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
