spring.application.name=notification-service

server.port=8083

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

aws.region=${AWS_REGION:eu-west-1}
app.sqs.order-events-queue-url=${ORDER_EVENTS_QUEUE_URL:}
