spring.application.name=notification-service

server.port=8083

aws.region=${AWS_REGION:eu-west-1}
sqs.queue.url=${SQS_QUEUE_URL:http://localhost:4566/000000000000/order-created-queue}
sqs.endpoint=${SQS_ENDPOINT:}
sqs.polling.enabled=${SQS_POLLING_ENABLED:true}
sqs.polling.delay-ms=${SQS_POLLING_DELAY_MS:5000}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
